language : node_js
node_js :
 - stable
install:
 - npm install
script:
 - ganache-cli > /dev/null &
 - sleep 5
 - npm run migrate
 - npm run test

after_script: "npx nyc report --reporter=text-lcov | npx coveralls"
