language : node_js
node_js :
 - stable
install:
 - npm install
 - npm install forever
script:
 - npx forever ./cli/run-ganache-cli.js
 - npm run migrate
 - npm run test

after_script: "npx nyc report --reporter=text-lcov | npx coveralls"
